services:
  plexcards:
    build:
      context: .
      dockerfile: Dockerfile
    image: plexcards:latest
    container_name: plexcards
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache
      - ./custom_fonts:/app/custom_fonts
